hydra:
  run:
    dir: /data/homezvol2/afeeney/crsp/ai4ts/afeeney/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# These must set by the user.
data_base_dir: /data/homezvol2/afeeney/crsp/ai4ts/share/
log_dir: /data/homezvol2/afeeney/crsp/ai4ts/afeeney/train_log/

test_only: False

defaults:
  - _self_
  - dataset: PB_WallSuperHeat
  - experiment: temp_fno
