# NOTE: The data_base_dir must be set by the user
# Either explicitly set it in this file or set it as a command-line argument
# when running the train script.
data_base_dir: /share/crsp/lab/amowli/share/BubbleML2
log_dir: /dfs6/pub/nsankar1/res_exp/BubbleML/logs

train: True
test: True

model_checkpoint:

defaults:
  - _self_
  - dataset: PB_WallSuperHeat
  - experiment: experimental/cno/pb_temp_upscale
