hydra:
  run:
    dir: /data/homezvol2/afeeney/crsp/ai4ts/afeeney/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# These should be overriden by the user to point to the location
# where the dataset was downloaded.
data_base_dir: /data/homezvol2/afeeney/crsp/ai4ts/share/BubbleML
log_dir: /data/homezvol2/afeeney/crsp/ai4ts/afeeney/train_log/

train: True
test: True

model_checkpoint:

defaults:
  - _self_
  - dataset: PB_WallSuperHeat
  - experiment: temp_unet2d
